/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Farisya
 */
public class adminView extends javax.swing.JFrame {

    /**
     * Creates new form adminView
     */
    public adminView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void klikDataUser(ActionListener a) {
        datauserbutton.addActionListener(a);
    }

    public void klikDataBibit(ActionListener a) {
        databibitbutton.addActionListener(a);
    }

    public void klikEditData(ActionListener a) {
        editButton.addActionListener(a);
    }
    public void klikDeleteData(ActionListener a) {
        deleteButton.addActionListener(a);
    }

    public void klikAddData(ActionListener a) {
        addButton.addActionListener(a);
    }

    public void setUname(String username) {
        usernamelabel.setText(username);

    }

    public void dashboardView() {
        datauser.setVisible(false);
        datalain.setVisible(false);
        dataLabel.setText("Welcome to AdminHome");
        pathlabel.setText("Admin / Home");
        editButton.setVisible(false);
        addButton.setVisible(false);
        deleteButton.setVisible(false);

    }

    public void dataUserView() {
        datauser.setVisible(true);
        datalain.setVisible(false);
        dataLabel.setText("Data User");
        pathlabel.setText("Admin / Home / DataUser");
        editButton.setVisible(true);
        deleteButton.setVisible(true);
        editButton.setEnabled(false);
        deleteButton.setEnabled(false);
        addButton.setVisible(true);
    }

    public void dataRekapView() {
        datauser.setVisible(false);
        datalain.setVisible(true);
        dataLabel.setText("Data Lain");
        pathlabel.setText("Admin / Home / DataLain");
        editButton.setVisible(true);
        addButton.setVisible(true);
        deleteButton.setVisible(true);
        editButton.setEnabled(false);
        deleteButton.setEnabled(false);
    }

    public void showTabelUser(DefaultTableModel tm) {
        tabeluser.setModel(tm);
    }

    public void showTabelBibit(DefaultTableModel tm) {
        tabelbibit.setModel(tm);
    }

    public int getSelectedRowUser() {
        int baris = tabeluser.getSelectedRow();
        return baris;
    }

    public int getSelectedRowBibit() {
        int baris = tabelbibit.getSelectedRow();
        return baris;
    }

    public void disableButton() {
        editButton.setEnabled(false);
        deleteButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        databibitbutton = new javax.swing.JButton();
        levellabel = new javax.swing.JLabel();
        usernamelabel = new javax.swing.JLabel();
        datauserbutton = new javax.swing.JButton();
        datauser = new javax.swing.JScrollPane();
        tabeluser = new javax.swing.JTable();
        datalain = new javax.swing.JScrollPane();
        tabelbibit = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        pathlabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        dataLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(225, 225, 225));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(225, 225, 225));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        databibitbutton.setBackground(new java.awt.Color(59, 140, 180));
        databibitbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        databibitbutton.setForeground(new java.awt.Color(255, 255, 255));
        databibitbutton.setText("Rekap Bibit");
        databibitbutton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 225, 225)));
        databibitbutton.setBorderPainted(false);
        databibitbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        databibitbutton.setFocusPainted(false);
        databibitbutton.setHideActionText(true);
        databibitbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                databibitbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                databibitbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                databibitbuttonMouseExited(evt);
            }
        });
        databibitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databibitbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(databibitbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 40));

        levellabel.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        levellabel.setForeground(new java.awt.Color(255, 255, 255));
        levellabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        levellabel.setText("Admin");
        jPanel2.add(levellabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, 40));

        usernamelabel.setBackground(new java.awt.Color(204, 204, 255));
        usernamelabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernamelabel.setForeground(new java.awt.Color(204, 204, 255));
        usernamelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(usernamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 110, 20));

        datauserbutton.setBackground(new java.awt.Color(59, 140, 180));
        datauserbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        datauserbutton.setForeground(new java.awt.Color(255, 255, 255));
        datauserbutton.setText("Data User");
        datauserbutton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 225, 225)));
        datauserbutton.setBorderPainted(false);
        datauserbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        datauserbutton.setFocusPainted(false);
        datauserbutton.setHideActionText(true);
        datauserbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datauserbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                datauserbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                datauserbuttonMouseExited(evt);
            }
        });
        datauserbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datauserbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(datauserbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 200, 40));

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 700));

        datauser.setBorder(null);

        tabeluser.setBackground(new java.awt.Color(225, 225, 225));
        tabeluser.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tabeluser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeluser.setIntercellSpacing(new java.awt.Dimension(2, 2));
        tabeluser.setRowHeight(30);
        tabeluser.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tabeluser.setSelectionForeground(new java.awt.Color(0, 102, 153));
        tabeluser.setShowHorizontalLines(false);
        tabeluser.setShowVerticalLines(false);
        tabeluser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeluserMouseClicked(evt);
            }
        });
        datauser.setViewportView(tabeluser);

        bg.add(datauser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 1040, 460));

        datalain.setBorder(null);

        tabelbibit.setBackground(new java.awt.Color(225, 225, 225));
        tabelbibit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tabelbibit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelbibit.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tabelbibit.setSelectionForeground(new java.awt.Color(0, 102, 153));
        tabelbibit.setShowHorizontalLines(false);
        tabelbibit.setShowVerticalLines(false);
        tabelbibit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbibitMouseClicked(evt);
            }
        });
        datalain.setViewportView(tabelbibit);

        bg.add(datalain, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 1040, 460));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pathlabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pathlabel.setForeground(new java.awt.Color(225, 225, 225));
        jPanel1.add(pathlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 161, 20));

        deleteButton.setBackground(new java.awt.Color(245, 142, 142));
        deleteButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Delete Selected Data");
        deleteButton.setBorder(null);
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteButtonMouseExited(evt);
            }
        });
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, 140, 40));

        editButton.setBackground(new java.awt.Color(224, 193, 72));
        editButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.setText("Edit Selected Data");
        editButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 225, 225)));
        editButton.setBorderPainted(false);
        editButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButton.setFocusPainted(false);
        editButton.setHideActionText(true);
        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editButtonMouseExited(evt);
            }
        });
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        jPanel1.add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 150, 40));

        addButton.setBackground(new java.awt.Color(59, 140, 180));
        addButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add Data");
        addButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 225, 225)));
        addButton.setBorderPainted(false);
        addButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addButton.setFocusPainted(false);
        addButton.setHideActionText(true);
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addButtonMouseExited(evt);
            }
        });
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, 40));

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 1040, 100));

        dataLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        dataLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.add(dataLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 1040, 50));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void databibitbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_databibitbuttonMouseEntered
//        datalainbutton.setBackground(new Color(225, 225, 225));
        databibitbutton.setForeground(new Color(0, 102, 153));
    }//GEN-LAST:event_databibitbuttonMouseEntered

    private void databibitbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_databibitbuttonMouseExited
//        datalainbutton.setBackground(new Color(59, 140, 180));
        databibitbutton.setForeground(Color.WHITE);
    }//GEN-LAST:event_databibitbuttonMouseExited

    private void databibitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databibitbuttonActionPerformed
    }//GEN-LAST:event_databibitbuttonActionPerformed

    private void editButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseEntered
        editButton.setBackground(new Color(211, 181, 64));
    }//GEN-LAST:event_editButtonMouseEntered

    private void editButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseExited
        editButton.setBackground(new Color(224, 193, 72));
    }//GEN-LAST:event_editButtonMouseExited

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed

    private void datauserbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datauserbuttonMouseEntered
//        datauserbutton.setBackground(new Color(225, 225, 225));
        datauserbutton.setForeground(new Color(0, 102, 153));
    }//GEN-LAST:event_datauserbuttonMouseEntered

    private void datauserbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datauserbuttonMouseExited
//        datauserbutton.setBackground(new Color(59, 140, 180));
        datauserbutton.setForeground(Color.WHITE);
    }//GEN-LAST:event_datauserbuttonMouseExited

    private void datauserbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datauserbuttonActionPerformed

    }//GEN-LAST:event_datauserbuttonActionPerformed

    private void deleteButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseEntered
        deleteButton.setBackground(new Color(230, 132, 132));
    }//GEN-LAST:event_deleteButtonMouseEntered

    private void deleteButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseExited
        deleteButton.setBackground(new Color(245, 142, 142));
    }//GEN-LAST:event_deleteButtonMouseExited

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void addButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseEntered
        addButton.setBackground(new Color(53, 121, 154));
    }//GEN-LAST:event_addButtonMouseEntered

    private void addButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseExited
        addButton.setBackground(new Color(59, 140, 180));
    }//GEN-LAST:event_addButtonMouseExited

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void datauserbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datauserbuttonMouseClicked
        datauserbutton.setBackground(new Color(225, 225, 225));
        datauserbutton.setForeground(new Color(0, 102, 153));
        databibitbutton.setBackground(new Color(59, 140, 180));

    }//GEN-LAST:event_datauserbuttonMouseClicked

    private void databibitbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_databibitbuttonMouseClicked
        databibitbutton.setBackground(new Color(225, 225, 225));
        databibitbutton.setForeground(new Color(0, 102, 153));
        datauserbutton.setBackground(new Color(59, 140, 180));

    }//GEN-LAST:event_databibitbuttonMouseClicked

    private void tabeluserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeluserMouseClicked
        editButton.setEnabled(true);
        deleteButton.setEnabled(true);
    }//GEN-LAST:event_tabeluserMouseClicked

    private void tabelbibitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbibitMouseClicked
        editButton.setEnabled(true);
        deleteButton.setEnabled(true);
    }//GEN-LAST:event_tabelbibitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JButton databibitbutton;
    private javax.swing.JScrollPane datalain;
    private javax.swing.JScrollPane datauser;
    private javax.swing.JButton datauserbutton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel levellabel;
    private javax.swing.JLabel pathlabel;
    private javax.swing.JTable tabelbibit;
    private javax.swing.JTable tabeluser;
    private javax.swing.JLabel usernamelabel;
    // End of variables declaration//GEN-END:variables
}
