/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Farisya
 */
public class mainView extends javax.swing.JFrame {

    /**
     * Creates new form mainViews
     */
    public mainView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public String getUsername() {
        String username = usernamefield.getText();
//      System.out.println("' " + username + " '");
        return username;
    }

    public String getPassword() {
        String pass = passwordfield.getText();
//      System.out.println("' " + username + " '");
        return pass;
    }

    public void klikLogin(ActionListener ml) {
        loginbutton.addActionListener(ml);
    }

    public void tampilPesan(String pesan) {
        JOptionPane.showMessageDialog(this, pesan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        crlabel = new javax.swing.JLabel();
        SignInLabel = new javax.swing.JLabel();
        SignInLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        closebutton = new javax.swing.JPanel();
        closelabel = new javax.swing.JLabel();
        usernamefield = new javax.swing.JTextField();
        passwordlabel = new javax.swing.JLabel();
        usernamelabel = new javax.swing.JLabel();
        SignInLabel1 = new javax.swing.JLabel();
        passwordfield = new javax.swing.JPasswordField();
        loginbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(225, 225, 225));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(0, 102, 153));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crlabel.setForeground(new java.awt.Color(204, 204, 255));
        crlabel.setText("Powered by Team 1A");
        sidebar.add(crlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        SignInLabel.setBackground(new java.awt.Color(0, 102, 153));
        SignInLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        SignInLabel.setForeground(new java.awt.Color(204, 204, 255));
        SignInLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignInLabel.setText("Welcome To");
        sidebar.add(SignInLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 220, 40));

        SignInLabel2.setBackground(new java.awt.Color(0, 102, 153));
        SignInLabel2.setFont(new java.awt.Font("Segoe UI Light", 2, 36)); // NOI18N
        SignInLabel2.setForeground(new java.awt.Color(255, 255, 255));
        SignInLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignInLabel2.setText("Fish.in");
        sidebar.add(SignInLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ikan.png"))); // NOI18N
        sidebar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 360));

        bg.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 451));

        closebutton.setBackground(new java.awt.Color(0, 102, 153));
        closebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closebutton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closelabel.setBackground(new java.awt.Color(204, 204, 255));
        closelabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        closelabel.setForeground(new java.awt.Color(255, 255, 255));
        closelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closelabel.setText("X");
        closelabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closelabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closelabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closelabelMouseExited(evt);
            }
        });
        closebutton.add(closelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        bg.add(closebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 0, 30, 30));

        usernamefield.setBackground(new java.awt.Color(225, 225, 225));
        usernamefield.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        usernamefield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernamefield.setToolTipText("username");
        usernamefield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));
        usernamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamefieldActionPerformed(evt);
            }
        });
        bg.add(usernamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 220, 30));

        passwordlabel.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        passwordlabel.setText("Password");
        bg.add(passwordlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        usernamelabel.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        usernamelabel.setText("Username");
        bg.add(usernamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        SignInLabel1.setBackground(new java.awt.Color(0, 102, 153));
        SignInLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        SignInLabel1.setForeground(new java.awt.Color(102, 102, 102));
        SignInLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignInLabel1.setText("Sign In");
        bg.add(SignInLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 140, 50));

        passwordfield.setBackground(new java.awt.Color(225, 225, 225));
        passwordfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordfield.setToolTipText("password");
        passwordfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));
        bg.add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 220, 30));

        loginbutton.setBackground(new java.awt.Color(0, 102, 153));
        loginbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginbutton.setForeground(new java.awt.Color(255, 255, 255));
        loginbutton.setText("Sign In");
        loginbutton.setBorder(null);
        loginbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginbuttonMouseExited(evt);
            }
        });
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        bg.add(loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamefieldActionPerformed

    private void closelabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closelabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closelabelMouseClicked

    private void closelabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closelabelMouseEntered
        closebutton.setBackground(new Color(204, 204, 255));
    }//GEN-LAST:event_closelabelMouseEntered

    private void closelabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closelabelMouseExited
        closebutton.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_closelabelMouseExited

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void loginbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbuttonMouseEntered
        loginbutton.setBackground(new Color(204, 204, 255));
        loginbutton.setForeground(Color.black);
    }//GEN-LAST:event_loginbuttonMouseEntered

    private void loginbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbuttonMouseExited
        loginbutton.setBackground(new Color(0, 102, 153));
        loginbutton.setForeground(Color.WHITE);
    }//GEN-LAST:event_loginbuttonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SignInLabel;
    private javax.swing.JLabel SignInLabel1;
    private javax.swing.JLabel SignInLabel2;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel closebutton;
    private javax.swing.JLabel closelabel;
    private javax.swing.JLabel crlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginbutton;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JPanel sidebar;
    private javax.swing.JTextField usernamefield;
    private javax.swing.JLabel usernamelabel;
    // End of variables declaration//GEN-END:variables
}
